# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://shumingpeh.github.io/
baseurl: /portfolio/
title: Senior Machine Learning Engineer • ShuMing Peh
author: Shu Ming Peh
description: Senior Machine Learning Engineer • ShuMing Peh
avatar: profile.jpeg
email: shuming.peh@gmail.com
github: shumingpeh/ # username
twitter: username
linkedin: shuming-peh
stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: username


# needed for travis-ci build
exclude: [vendor]
